### ISSUE TITLE
plus-pro-components组件引入后docker镜像打包失败

### ISSUE THREAD

**Issue by zyj010zyj** [nineaiyu/xadmin-client#10]
xadmin-client-build  | transforming...
xadmin-client-build  | ✓ 13 modules transformed.
xadmin-client-build  | x Build failed in 2.67s
xadmin-client-build  | error during build:
xadmin-client-build  | Error: [vite]: Rollup failed to resolve import "plus-pro-components/index.css" from "/app/src/main.ts".
xadmin-client-build  | This is most likely unintended because it can break your application at runtime.
xadmin-client-build  | If you do want to externalize this module explicitly add it to
xadmin-client-build  | `build.rollupOptions.external`
xadmin-client-build  |     at viteWarn (file:///app/node_modules/.pnpm/vite@5.1.4_@types+node@20.11.20_sass@1.71.1/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:67078:27)
xadmin-client-build  |     at onRollupWarning (file:///app/node_modules/.pnpm/vite@5.1.4_@types+node@20.11.20_sass@1.71.1/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:67106:9)      
xadmin-client-build  |     at onwarn (file:///app/node_modules/.pnpm/vite@5.1.4_@types+node@20.11.20_sass@1.71.1/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:66810:13)
xadmin-client-build  |     at file:///app/node_modules/.pnpm/rollup@4.12.0/node_modules/rollup/dist/es/shared/node-entry.js:18308:13
xadmin-client-build  |     at Object.logger [as onLog] (file:///app/node_modules/.pnpm/rollup@4.12.0/node_modules/rollup/dist/es/shared/node-entry.js:19965:9)
xadmin-client-build  |     at ModuleLoader.handleInvalidResolvedId (file:///app/node_modules/.pnpm/rollup@4.12.0/node_modules/rollup/dist/es/shared/node-entry.js:18909:26)
xadmin-client-build  |     at file:///app/node_modules/.pnpm/rollup@4.12.0/node_modules/rollup/dist/es/shared/node-entry.js:18867:26
xadmin-client-build  |  ELIFECYCLE  Command failed with exit code 1.
xadmin-client-build exited with code 1    根据报错解决办法添加额外组件只能解决plus-pro-components/index.css的导包问题  余下包的引用仍旧会出现问题

**Comment by nineaiyu** [comment]
有个打包脚本```build.sh```
内容如下：
```shell
#!/bin/bash
#
#
# clean old build docker and image
docker rm -f xadmin-client-build
docker image rm xadmin-client-build

# build web
docker compose up xadmin-client-build
```
是通过这个脚本进行打包的么？我这里在Linux平台测试是没有问题的

**Comment by zyj010zyj** [comment]
那可能是WIN10环境不兼容或者其他原因导致的
