### ISSUE TITLE
部门管理页面的分页会导致展示有问题

### ISSUE THREAD

**Issue by trajectoryend** [nineaiyu/xadmin-client#15]
图一为分页数为10，少于数据数量36， 表格数据直接展示（并没有按照树形展示）
![image](https://github.com/nineaiyu/xadmin-client/assets/168240719/b1d6524f-11f3-4c39-8ca8-2efee8ff8fdb)

此时点击新增、归属部门，也只能拉取10条数据，如下图：
![image](https://github.com/nineaiyu/xadmin-client/assets/168240719/2601fb43-81a5-40ae-96e8-db79e45b6edb)

此处建议新增的时候，分页传大一些如100000（当前只能选择分页给出的10条数据），

现在只能通过调大外侧页面的pagesize才可以正常选择所有部门，但是外测最大只能调成100，见下图：
![image](https://github.com/nineaiyu/xadmin-client/assets/168240719/14e167ba-4fd8-473a-9fea-048c0754f5a1)

**Comment by nineaiyu** [comment]
[最新代码](https://github.com/nineaiyu/xadmin-client/commit/9b50d8339d8cbe787154597b44c0fca4f9fbc1da) 已修复
