### ISSUE TITLE
【BUG反馈】系统管理-权限管理-数据权限页面中，新增和编辑里的新增规则列表，属性名获取不全

### ISSUE THREAD

**Issue by trajectoryend** [nineaiyu/xadmin-client#16]
系统管理-权限管理-数据权限页面中，新增和编辑里的新增规则列表，属性名只能拿到6个值，猜测是接口分页导致的。
![image](https://github.com/nineaiyu/xadmin-client/assets/168240719/2ddfa7e6-c29e-4bfa-b855-2631428d567b)

**Comment by nineaiyu** [comment]
演示模式里面是正常的，你浏览器打开调试模式，看下该页面的请求是否正常
![image](https://github.com/nineaiyu/xadmin-client/assets/19207867/c3e31463-4061-4c20-9ce9-428469503e80)
