### ISSUE TITLE
可优化项目：选人的select选出来的是id，不容易区分，建议修改为用户的昵称；另外搜索类型的人员过滤修改为选人组件

### ISSUE THREAD

**Issue by trajectoryend** [nineaiyu/xadmin-client#17]
![image](https://github.com/nineaiyu/xadmin-client/assets/168240719/9865f2b8-774e-4676-995d-bfa6c0ca520a)
前端选人组件，选出来的是id，不容易区分，建议修改为用户的昵称。

另外对于搜索类型的人员过滤，建议修改成选人组件，因为基本无法记录去搜索。
![image](https://github.com/nineaiyu/xadmin-client/assets/168240719/099fde3f-ca9a-4827-82e7-b02f1a4486a1)

**Comment by nineaiyu** [comment]
最新代码已经支持，可在演示模式下进行操作预览
