### ISSUE TITLE
可优化项：发布消息之后，需要浏览器刷新才可以显示未读消息的徽标，建议此处修改为定时获取，便于用户及时获取未读信息

### ISSUE THREAD

**Issue by trajectoryend** [nineaiyu/xadmin-client#18]
发布消息之后，需要浏览器刷新才可以显示未读消息的徽标，建议此处修改为定时获取，便于用户及时获取未读信息
![image](https://github.com/nineaiyu/xadmin-client/assets/168240719/8d508883-e35b-4da5-a23e-780a553b2504)

**Comment by nineaiyu** [comment]
最新版本 v2.3.1 已经支持，具体可在预览网站体验
