### ISSUE TITLE
前端定时任务页面重定向至首页

### ISSUE THREAD

**Issue by zyj010zyj** [nineaiyu/xadmin-client#3]
点击定时任务按钮后打开了新的标签页 但是标签页内部会自动重新加载一遍首页代码以及左侧菜单栏,观察日志显示在访问/system/flower后又重新访问首页welcome页面了   而且我观察git内system下并无flower   后端的celert flower正常启动了  请问一下这是哪里的问题

**Comment by zyj010zyj** [comment]
![Snipaste_2024-04-09_14-38-42](https://github.com/nineaiyu/xadmin-client/assets/142365349/6cd59720-820f-49ba-888c-5e5a3911453c)
![Snipaste_2024-04-09_14-39-23](https://github.com/nineaiyu/xadmin-client/assets/142365349/2aba0c33-5fef-4ac7-836d-816c3ac62936)
我这边的效果是这样的

**Comment by zyj010zyj** [comment]
此外我还有几个问题需要请教:
1.另外关于权限路由的设置问题   我不太清楚是否是因为我添加新页面的步骤有问题    他会出现再添加页面后并无自动加载新增的路由相关选项   且重启也无效  一般我会在菜单管理内进行新增 而后在表名结尾为menu找到字段名Path手动输入路径  这样可以正常访问  在新增好多页面后的某一天我发现他动态生成了权限路由  但是在我替换后页面就无法正常访问了
2.对于权限管理中的部门权限和角色权限的关联我可能摸索的还不太够  所以存在疑问需要请教 :
-  在部门权限分配中 或与且代表什么  
- 为什么部门角色是可以多选的
- 数据权限选项中的各类选项代表什么功能
希望能在闲暇时对我的问题进行解答

**Comment by nineaiyu** [comment]
> 点击定时任务按钮后打开了新的标签页 但是标签页内部会自动重新加载一遍首页代码以及左侧菜单栏,观察日志显示在访问/system/flower后又重新访问首页welcome页面了 而且我观察git内system下并无flower 后端的celert flower正常启动了 请问一下这是哪里的问题

定时任务是通过 common/celery/flower.py 这个代码进行代理的，需要后端启动flower服务，才可以正常将数据代理过了

**Comment by nineaiyu** [comment]
你上面说的第一个问题，这个可能是缓存导致的，之前存在缓存问题，就是修改菜单之后，管理员的菜单缓存未失效问题，这个问题在3.19号提交已经解决，也可以通过清清空redis缓存

权限中的或与切 仅针对 多个数据权限配置， 且模式 表示多个数据权限同时满足条件，或模式 表示满足任意一个条件

**Comment by zyj010zyj** [comment]
> > 点击定时任务按钮后打开了新的标签页 但是标签页内部会自动重新加载一遍首页代码以及左侧菜单栏,观察日志显示在访问/system/flower后又重新访问首页welcome页面了 而且我观察git内system下并无flower 后端的celert flower正常启动了 请问一下这是哪里的问题
> 
> 定时任务是通过 common/celery/flower.py 这个代码进行代理的，需要后端启动flower服务，才可以正常将数据代理过了

我使用了celery -A server worker和celery -A server flower 来进行启动  两个启动日志表示启动成功 默认不指定端口启动的是5555  即使指定端口为5566 但是我仍旧无法访问   如果通过common/celery/flower.py进行了代理 但是看起来这个代码里的内容只是用于定义视图      仍旧无法访问 本地执行会重定向到首页   docker内执行会显示404 这显然是不正常的 请问我哪个步骤出现了错误

**Comment by nineaiyu** [comment]
这个celery服务和Django服务是在同一个服务器或者容器么？

**Comment by nineaiyu** [comment]
```python -m celery -A server flower -logging=info --url_prefix=/api/flower --auto_refresh=False  --address=127.0.0.1 --port=5566``` 这个命令可以单独启动flower,需要和django在同一个环境内启动

**Comment by zyj010zyj** [comment]
> `python -m celery -A server flower -logging=info --url_prefix=/api/flower --auto_refresh=False --address=127.0.0.1 --port=5566` 这个命令可以单独启动flower,需要和django在同一个环境内启动

都是在我本地执行的 运行日志我发送了  无论是直接访问5566端口还是前端页面点击   仍旧无法访问  
[file1.txt](https://github.com/nineaiyu/xadmin-client/files/14994607/file1.txt)
[file2.txt](https://github.com/nineaiyu/xadmin-client/files/14994609/file2.txt)
![Snipaste_2024-04-16_17-10-46](https://github.com/nineaiyu/xadmin-client/assets/142365349/71418fc5-c796-4975-ab4c-edeb089fdfbe)
![Snipaste_2024-04-16_17-11-14](https://github.com/nineaiyu/xadmin-client/assets/142365349/f7cde987-e690-421b-99dd-39efcff38bb9)
我本地的防火墙已经全部关闭了   这个重定向很奇怪

**Comment by nineaiyu** [comment]
http://127.0.0.1:5566/api/flower/  本地浏览器可以访问这个么？

**Comment by nineaiyu** [comment]
不清楚是哪里的问题，可能是Windows下flower不太兼容 😭

**Comment by zyj010zyj** [comment]
> 不清楚是哪里的问题，可能是Windows下flower不太兼容 😭

不太清楚了  主要本地写demo可以打开     如果docker调试的话  应该需要在dockerfile内添加运行代码吧  我想知道为什么git的docker相关文件没有celery启动部分的代码

**Comment by nineaiyu** [comment]
common/management/commands  你看下里面的代码，这个是启动服务的时候```python manage.py start all``` 执行的逻辑

**Comment by zyj010zyj** [comment]
> common/management/commands 你看下里面的代码，这个是启动服务的时候`python manage.py start all` 执行的逻辑

好的  非常感谢

**Comment by zyj010zyj** [comment]
我试着在docker容器内进行了访问   访问路径是http://localhost:8891/#/system/flower/     
![Snipaste_2024-04-17_16-02-47](https://github.com/nineaiyu/xadmin-client/assets/142365349/747c7225-891b-43fc-9e54-dfcb4486b4af)
而后我尝试访问http://localhost:8896/api/flower/  在最开始时确实正常打开了     如图
![Snipaste_2024-04-17_16-05-15](https://github.com/nineaiyu/xadmin-client/assets/142365349/01ddcdc0-cb73-4e47-bdd9-725bcdf8a6a3)
 我为了解决前端页面404的问题 添加了nginx并且在容器内启动  但是他并没有任何用处   再次使用后端端口访问时又成了401没有通过权限校验   我不太清楚为什么会这样    其次参照了后端文档中的nginx配置        proxy_pass http://127.0.0.1:28896;  我在想28896的2是错误输入还是正确的        而当我通过昨天的沟通想测试一下本地5566端口 进行http://127.0.0.1:5566/api/flower/访问时显示无法访问此网站127.0.0.1 拒绝了我们的连接请求。
  现在更懵了   麻烦您有空时帮忙解答一下我的困惑

**Comment by nineaiyu** [comment]
Windows上面无法正常运行celery flower，请使用Linux环境开发部署。
如果访问celery flowr 提示未授权，应该是开启了flower的授权，可以在启动celery flower的时候，去掉--basic-auth 参数
