### ISSUE TITLE
ui优化的小建议

### ISSUE THREAD

**Issue by casuallyone** [nineaiyu/xadmin-client#32]
1.可以使用vue-json-pretty优化相关表单编辑json字段的显示
![image](https://github.com/user-attachments/assets/1638d99a-d56a-4378-bbcc-4244ccb42fd8)
2. 登录时输入按Tab键输入不符合预期，在输入用户名和密码后，按Tab键会先跳到账户密码的menu，而不是验证码输入区
![image](https://github.com/user-attachments/assets/f0225b25-c9fb-4c38-93af-f15017c1c283)

**Comment by nineaiyu** [comment]
最新代码已经优化，可在演示平台查看
