### ISSUE TITLE
初始功能国际化汉化不完全

### ISSUE THREAD

**Issue by Hui3c** [nineaiyu/xadmin-client#36]
安装完成后部分国际化无法展示。当设置为英文后刷新页面又变回中文。
未进行任何配置，服务器部署正常
![2024-10-18_14-46-43_chrome](https://github.com/user-attachments/assets/d87a1e7d-8371-4162-83e5-661e1a2fa376)
![image](https://github.com/user-attachments/assets/9aad4d5c-0efa-4f0f-836a-2dcf1880fcaf)

**Comment by nineaiyu** [comment]
这种应该是没有编译国际化，需要执行这个命令 
```
python manage.py compilemessages
```
可参考文档：https://docs.dvcloud.xin/guide/installation-local.html
