### ISSUE TITLE
关于前端标签页显示问题

### ISSUE THREAD

**Issue by zyj010zyj** [nineaiyu/xadmin-client#9]
![image](https://github.com/nineaiyu/xadmin-client/assets/142365349/d7d4778f-5c0a-4e4b-a046-c1c3f60424aa)

我注意到在大约半个月前的更新后 菜单栏中文显示异常   是由于label删除导致的  
![image](https://github.com/nineaiyu/xadmin-client/assets/142365349/23c65a5e-c22e-467c-815a-bd26c3c54a98)
并且zh-CN.yaml  内容页做了部分删除

**Comment by nineaiyu** [comment]
菜单上面的label 存储在数据库里面，可以在这里修改，之前是 ```menus.hsUser```, 变成了现在的```menus.userManagement```
![image](https://github.com/nineaiyu/xadmin-client/assets/19207867/8392c22b-d3a1-4219-b51a-dae45bb5d3bb)
可以参考演示网站上面的菜单配置
